### ISSUE TITLE
Final group capstone - Book an Appointment

### ISSUE THREAD

**Issue by Rudy-Menekam** [Rudy-Menekam/Rentals-project-frontend#14]
Link to our kanban board - https://github.com/users/Rudy-Menekam/projects/3/views/1?layout=board
Our group is made up of four participants: @yash244466666 @chepkok3 @MarkoKermi  and myself

Screenshot of current Kanban board
![Screenshot from 2023-06-14 14-24-00](https://github.com/Rudy-Menekam/Car-Rentals/assets/30177437/73aa84f5-1f3d-4890-b5d0-88be817baa26)

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However there are some issues preventing me from giving the 👍 


## Highlights
- all tasks have descriptions 👍 
- Cover all of project requirements in issue 👍 
- Seems to like the times assigned/weights assigned are realistic 👍 

## Optional suggestions
- Please ensure the total weight of tasks for any individual team member is not significantly different in weight from another, ie, no team member should have a difference in weight of more than or equal to fine (or more than 4) when compared with any other team member.
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chepkok3** [comment]
Screenshot of our current Kanban board
<img width="1415" alt="Screenshot 2023-06-15 at 11 42 01" src="https://github.com/Rudy-Menekam/Car-Rentals/assets/78428936/073633ff-83b4-4f21-8b38-134b2aa5cacf">

**Comment by Meltrust** [comment]
Hi team,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The tasks' pointings are now more equal✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by chepkok3** [comment]
@Meltrust Thanks.
